### ISSUE TITLE
supporting edge labels?

### ISSUE THREAD

**Issue by wuyinjun-1993** [mayabechlerspeicher/TREE-G#1]
Hello, 
     Thanks for your great work on developing this! I am wondering whether the proposed model can incorporate edge labels as part of the model input. As far as I can see from the TU_MUTAG example, it seems to me that the edge labels are ignored.

**Comment by mayabechlerspeicher** [comment]
Thank you.
Indeed currently TREE-G does not support edge features. 
What would be an effective way to incorporate edge features was left for future research, and it will be a very interesting and useful extension to TREE-G.
One immediate naive solution you can try is to combine the edge features in the node features as a pre-processing step and feed this updated graph to TREE-G.

**Comment by wuyinjun-1993** [comment]
I see. Great. Thanks for your response! I will try your suggestions.
